specVersion: '0.0.1'
description: 'The project goal is to allow users to query the history of staking amount in Kusama/Polkadot.'
repository: ''

schema: './schema.graphql'

network:
  endpoint: wss://kusama.api.onfinality.io/public-ws
  # endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
  # endpoint: wss://kusama.api.onfinality.io/public-ws
  # dictionary: https://api.subquery.network/sq/subquery/dictionary-kusama

dataSources:
  - name: runtime
    kind: substrate/Runtime
    startBlock: 8900000 # Polkadot - 6900000
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
